### ISSUE TITLE
Issue Building on Windows 10

### ISSUE THREAD

**Issue by DeveloperPaul123** [ebenoist/libblinkstick#13]
Working on Windows 10 with Visual Studio 2013, I'm getting some link errors when trying to build the `blinkstick` CLI. 

The library itself builds fine but I get `hidapi` link errors when building the CLI:

![image](https://user-images.githubusercontent.com/6591180/37057539-b75bc0c6-2155-11e8-83e0-60c4b8bdc0bd.png)

But looking at my linker input for the `blinkstick` CLI, I can see the hidapi library is there. 
![image](https://user-images.githubusercontent.com/6591180/37057673-240df662-2156-11e8-8641-d1f29c2481e9.png)

Is there something I'm missing? I feel like it might be a dumb mistake but I can't see what it is. One thing I'll note is that I removed the requirement for `PkgConfig` and instead used [this](https://github.com/rpavlik/cmake-modules/blob/master/FindHIDAPI.cmake) CMake module to find `hidapi` and link the necessary libraries via CMake. 

I haven't tried using the `blinkstick` lib I built in another project. I'll try that next and update this issue.

**Comment by ebenoist** [comment]
Interesting. Honestly I've never built this library on anything other than OSX, but I'm eager to get this working on other platforms. I don't currently have access to Windows 10, so any help would be greatly appreciated.

**Comment by DeveloperPaul123** [comment]
@ebenoist Sounds like there's some work ahead of me!

The messages I'm getting typically are due to a library not being linked or something to that effect. The fact that visual studio is complaining about `hid_*` methods makes me think it could be the `hidapi` lib itself. I'll have to investigate further. 

Are you open to PRs to make this lib work on Windows?

**Comment by ebenoist** [comment]
Very open! Thank you for investigating and please let me know how I can help. I suspect that hidapi is not linking correctly, this may be a hidapi problem, but is also likely an issue with the cmake build itself for this project.

**Comment by DeveloperPaul123** [comment]
@ebenoist So turns out this was an issue of `hidapi` being built as `Win32` not x64. Building `hidapi` in `x64` did the trick. 

I'm now facing other issues where the blinkstick is found, but LED colors cannot be set. I'll file a separate issue for this and PR for some CMake setup changes.
