### ISSUE TITLE
Issue Setting LED Color with BlinkStick Pro With Smart Pixels

### ISSUE THREAD

**Issue by DeveloperPaul123** [ebenoist/libblinkstick#15]
Using the CLI I'm getting errors when trying to set the color of a single LED on a blinkstick pro.

I added some more debug log statements to the write color function. This is the output I'm getting with the `--debug` option passed to the CLI:

![image](https://user-images.githubusercontent.com/6591180/37101338-4b6d0a70-21f3-11e8-9c77-f06602874adc.png)

Looks like `hid_write` is returning -1. 

Note that this is def not hardware as I the Blinnkstick works using the `BlinkStickDotNet` library.

**Comment by DeveloperPaul123** [comment]
@ebenoist Any thoughts as to why this could be happening?

**Comment by ebenoist** [comment]
Honestly, I'm not sure, but I suspect this has something to do with a different mode that may need to be set for the blinkstick pro. This library has only been tested with the blinkstick 1 and the square at this point. I might grab a pro to test things out, but it'll be a few weeks before I can figure it out.

**Comment by DeveloperPaul123** [comment]
@ebenoist I see. We work with pros on a regular basis so if you point me in the right direction I can fix it/test it out. 

Did you figure out what needed to be set and what not from the open source firmware? Or do you have some other reference you looked at?

**Comment by ebenoist** [comment]
I usually reference the python implementation: https://github.com/arvydas/blinkstick-python

**Comment by ebenoist** [comment]
Those docs make sense, I had to do some pivots for supporting the square vs the blinkstick 1 as well, so it doesn't surprise me that we'll need to add more. 

As far as moving to C++/OO, this is something I'm less interested in. The goal of this library (for me) was to create a lowest common denominator library to interface with other languages that have a good FFI bridge. Using C++ complicates that goal.

**Comment by DeveloperPaul123** [comment]
>  I had to do some pivots for supporting the square vs the blinkstick 1 as well

Are you referring to the code in building the control message? 

As far as C++ goes, no worries. 

My question to you then is how you want to add in support for the blinkstick pro? As well as the ability to set the mode of the blinkstick?

**Comment by ebenoist** [comment]
Maybe a flag with the identifier of what _kind_ of blinkstick it is? So possibly an argument for find_blinkstick? 

Do you know if it identifies itself uniquely at all so we could use that as a pivot during writes?

**Comment by DeveloperPaul123** [comment]
@ebenoist 

I don't think the BlinkStick pro identifies differently than any other blinkstick. I think the differences lie in the mode that can be set for the blinkstick (the pro model supports mode 2 for "smart" LEDs). 

I've been giving this some thought and came up with the following:

* Add a `mode` variable (`uchar` or `enum`?) to `blinkstick_device`
* Add a `blinkstick_set_mode` function that will take in the device and the given mode (maybe use an `enum` for `mode` since there are only 3).
* Account for `mode` when setting the color of the blinkstick using the `mode` variable of the `blinkstick_device`.

One thing I'm not sure of how to handle is the payload when sending data to the blinkstick pro. It seems the payload size and structure changes slightly depending on the number of leds connected. I'll need to dig into the python code a bit more.

**Comment by ebenoist** [comment]
All of that makes sense to me. I'd swing enum to make the documentation a bit simpler. Having a pivot to write the payload differently based on mode doesn't bother me at all. 

Thanks again for looking into this.

**Comment by DeveloperPaul123** [comment]
@ebenoist No problem. Just to clarify does `I'd swing enum` mean to *not* use an enum? Just want to make sure I understand correctly.

**Comment by ebenoist** [comment]
Ha sorry. Yes, I'd prefer an enum for sure.

**Comment by DeveloperPaul123** [comment]
@ebenoist I'm currently working on this issue, but I can't seem to get a valid handle to the blink stick device. `hid_open_path()` always returns a null handle. Any idea why that might be? Have you ever tested your code on windows?
