### ISSUE TITLE
Proposal: Return booleans from all functions that require a blinkstick handle

### ISSUE THREAD

**Issue by DeveloperPaul123** [ebenoist/libblinkstick#18]
In all functions that take a `blinkstick_device` pointer, it may be good to return a boolean to indicate if the function was able to execute the action successfully. 

For example, consider `void blinkstick_off(blinkstick_device* blinkstick, int index)`. 

Currently there is no way of knowing (purely from software) if the blinkstick LED was infact turned off. What if the HID device handle is `NULL`? (Currently there is no check for that either). 

Instead I propose that the function return a boolean to indicate if the process of changing the LED color was successful or not.

**Comment by ebenoist** [comment]
Works for me!

**Comment by DeveloperPaul123** [comment]
PRs coming soon...

**Comment by ebenoist** [comment]
Awesome! Thank you so much!
